name: Networks
author: Sefiraat and DoctorWil
description: A powerful item storage and movement network system for Slimefun4 | Refactored & Bug Fixed by wilianlimasantos
main: io.github.sefiraat.networks.Networks
website: https://github.com/wilianlimasantos/Networks-3.0
version: ${project.version}
api-version: 1.21
folia-supported: true
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - Netheopoiesis
  - SlimeHUD
  - mcMMO
commands:
  networks:
    aliases: [ntw]
    description: Networks plugin command
    usage: /networks <fillquantum|setquantum> <amount>
permissions:
  networks.admin:
    description: Allows access to admin commands
    default: op